clone:
  depth: full

definitions:
  steps:
    - step: &audit
        name: Audit Packages
        image: node:lts
        script:
          - corepack enable
          - yarn dlx audit-ci@^7 --config ./audit-ci.jsonc | tee audit-report.json
        artifacts:
          - audit-report.json
pipelines:
  default:
    - step:
        <<: *audit
