  feature/Whatsapp[m
  feature/pulseem-WA-13-manage-whatsApp-templates-ui[m
  feature/pulseem-WA-4-whatsapp-add-header-navigation[m
  feature/pulseem-WA-7-action-buttons[m
  feature/pulseem-WA-71-create-template-editor[m
  feature/pulseem-WA-73-quick-reply[m
  feature/pulseem-WA-77-creating-json[m
  feature/pulseem-WA-79-sync-component[m
  feature/pulseem-WA-api-integration[m
  feature/pulseem-WA-api-save-campaign[m
  feature/pulseem-WA-api-send-campaign[m
  feature/pulseem-WA-dynamic-fields-links[m
  feature/pulseem-WA-management-PAI[m
  feature/pulseem-WA-management-pages-API[m
  feature/pulseem-WA-management-pages-UI[m
  feature/pulseem-WA-page-1-send-whatsapp-campaign[m
  feature/pulseem-WA-page-2/2-send-whatsapp-campaign[m
* [32mfeature/pulseem-WA-template-apis[m
  feature/pulseem-WA-whatsapp-chat-modal-ui[m
  feature/pulseem-WA-whatsapp-chat-ui[m
  feature/pulseem-WA-whatsapp-mobile-preview[m
  master[m
  master-architecture[m
