export interface PurchaseReport {
    PageName: string;
    ProductName: string;
    Amount: number;
    TotalPrice: number;
    PurchaseStatus: string;
    PurchaseDate: Date | string;
    ClientID: number;
    Email: string;
    FirstName: string;
    LastName: string;
    Telephone: string;
    Cellphone: string;
    Address: string;
    City: string;
    State: string;
    Country: string;
    Zip: string;
    Company: string;
    BirthDate: Date | string;
    ExtraDate1: Date | string;
    ExtraDate2: Date | string;
    ExtraDate3: Date | string;
    ExtraDate4: Date | string;
    ExtraField1: string;
    ExtraField2: string;
    ExtraField3: string;
    ExtraField4: string;
    ExtraField5: string;
    ExtraField6: string;
    ExtraField7: string;
    ExtraField8: string;
    ExtraField9: string;
    ExtraField10: string;
    ExtraField11: string;
    ExtraField12: string;
    ExtraField13: string;
}