/**
 * Generated by orval v6.4.0 🍺
 * Do not edit manually.
 * Events API
 * OpenAPI spec version: 0.0.1
 */
import axios, {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'

import { siteTrackingURL } from '../config/index';

export const AXIOS_INSTANCE = axios.create({ baseURL: siteTrackingURL });

export interface InternalServerErrorDto {
  /** HTTP Status Code */
  statusCode: number;
  /** HTTP Error description */
  error: string;
  /** Detailed error message */
  message: string;
}

export interface UnprocessableErrorDto {
  /** HTTP Status Code */
  statusCode: number;
  /** HTTP Error description */
  error: string;
  /** Detailed error message */
  message: string;
}

export interface UnauthorizedErrorDto {
  /** HTTP Status Code */
  statusCode: number;
  /** HTTP Error description */
  error: string;
  /** Detailed error message */
  message: string;
}

export type CreateEventDefinitionOutputDtoActionType = 'ADD_CLIENTS_TO_GROUP';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventDefinitionOutputDtoActionType = {
  ADD_CLIENTS_TO_GROUP: 'ADD_CLIENTS_TO_GROUP' as CreateEventDefinitionOutputDtoActionType,
};

export type CreateEventDefinitionOutputDtoEventName = 'PAGE_VIEW';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventDefinitionOutputDtoEventName = {
  PAGE_VIEW: 'PAGE_VIEW' as CreateEventDefinitionOutputDtoEventName,
};

export interface CreateEventDefinitionOutputDto {
  domain: string;
  eventName: CreateEventDefinitionOutputDtoEventName;
  actionType: CreateEventDefinitionOutputDtoActionType;
  metadata: EventMetadataDto;
}

export type CreateEventDefinitionInputDtoActionType = 'ADD_CLIENTS_TO_GROUP';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventDefinitionInputDtoActionType = {
  ADD_CLIENTS_TO_GROUP: 'ADD_CLIENTS_TO_GROUP' as CreateEventDefinitionInputDtoActionType,
};

export type CreateEventDefinitionInputDtoEventName = 'PAGE_VIEW';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventDefinitionInputDtoEventName = {
  PAGE_VIEW: 'PAGE_VIEW' as CreateEventDefinitionInputDtoEventName,
};

export interface CreateEventDefinitionInputDto {
  domain: string;
  eventName: CreateEventDefinitionInputDtoEventName;
  actionType: CreateEventDefinitionInputDtoActionType;
  metadata: EventMetadataDto;
}

export type EventMetadataDtoOperatorKey = 'CONTAINS' | 'NOT_CONTAINS' | 'EXACT';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventMetadataDtoOperatorKey = {
  CONTAINS: 'CONTAINS' as EventMetadataDtoOperatorKey,
  NOT_CONTAINS: 'NOT_CONTAINS' as EventMetadataDtoOperatorKey,
  EXACT: 'EXACT' as EventMetadataDtoOperatorKey,
};

export interface EventMetadataDto {
  operatorKey: EventMetadataDtoOperatorKey;
  operatorValue: string;
  groupIds?: number[];
}




/**
* @summary Create event definition
*/
export const eventsControllerCreate = <TData = AxiosResponse<CreateEventDefinitionOutputDto>>(
  createEventDefinitionInputDto: CreateEventDefinitionInputDto, options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(
    `/events`,
    createEventDefinitionInputDto, options
  );
}

