import { SubAccount } from '../SubAccount/SubAccounts';
import { DirectAccountModel } from './DirectAccount';

export interface Account {
    AccountID: number;
    CompanyName: string;
    Address: string;
    Telephone: string;
    ContactName: string;
    BirthDate: Date | string | null;
    CellPhone: string;
    City: string;
    ZipCode: number | null;
    Country: string;
    WebSite: string;
    Industry: string;
    TimeZone: number | null;
    CompanyNumber: string;
    Email: string;
    Comment: string;
    AddPulseemSufixToMail: boolean | null;
    PriceListID: number | null;
    BulkListID: number | null;
    LandPagePriceListID: number | null;
    SMSPriceListID: number | null;
    SendAmountForSeniority: number | null;
    WeeksPeriodForSeniority: number | null;
    HasSeniority: boolean | null;
    CreationDate: Date | string;
    Discount: number | null;
    PrePaidBulkLeft: number | null;
    IsPaying: boolean | null;
    ReferrerID: number | null;
    SMSCredits: number | null;
    SMSProvider: number | null;
    GoogleAnalyticsCode: string;
    KbPerEmailCreditFactor: number | null;
    IsCreditBased: boolean | null;
    AffiliateID: string | null;
    GifSeconds: number | null;
    SmsLength: number | null;
    MmsCredits: number | null;
    MmsProvider: number | null;
    AccountManager: string;
    HasSPF: boolean | null;
    HLRCredits: number;
    Language: string;
    IsRecipientRemovalNotification: boolean | null;
    RecipientRemovalNotificationEmail: string;
    BillingCCEmail: string;
    AddPulseemSufixToPage: boolean | null;
    AccountFeatures: number[];
    SubAccounts: SubAccount[];
    DirectAccounts: DirectAccountModel;
    IsBillingAccount: boolean;
    AddCreditCardAllowed: boolean;
}