import { CSSProperties } from "@material-ui/core/styles/withStyles";
import { TYPE_JSX } from "./common";
export type DialogOptions = {
  childrenPadding?: boolean;
  open: boolean;
  title: any;
  icon?: any;
  children: TYPE_JSX;
  showDivider?: boolean;
  onClose?: Function;
  onCancel?: Function;
  onConfirm?: Function;
  renderButtons?: any;
  renderTitle?: any;
  disableBackdropClick?: boolean;
  customContainerStyle?: Object | string | null;
  paperStyle?: Object | string | null;
  childrenStyle?: Object | string | null;
  contentStyle?: Object | string | null;
  cancelText?: string;
  confirmText?: string;
  showDefaultButtons?: boolean;
  style?: CSSProperties | undefined;
  exitButton?: any;
  maxHeight?: string | number | undefined;
  reduceTitle?: boolean;
};

export type Slider_Dialog_PropTypes = {
  slides: any[];
  isOpen: boolean;
  VARIABLE_SLIDE_HEIGHTS?: null | String[];
  navigationButtons?: boolean;
  defaultButtons?: boolean;
  customButtons?: TYPE_JSX | string;
  confirmText?: string;
  backText?: string;
  onClose?: Function;
  onConfirm?: Function;
  rollBack?: boolean;
  currentStep?: number;
  setCurrentStep?: Function;
};
