export const StaticData = [
  {
    ActiveCell: 411,
    ActiveEmails: 275,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 842297,
    InvalidCell: 850,
    InvalidEmails: 641,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 256,
    Recipients: 917,
    RemovedCell: 132,
    RemovedEmails: 102,
    RestrictedEmails: 454,
    SubAccountID: 852,
    TotalRecipients: 123,
    GroupName: "Mayo Kim",
    UpdatedDate: "2018-09-22T03:29:28 -06:-30",
    CreatedDate: "2020-03-30T07:49:24 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: 1
  },
  {
    ActiveCell: 517,
    ActiveEmails: 651,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 448132,
    InvalidCell: 955,
    InvalidEmails: 407,
    IsDynamic: false,
    IsTestGroup: null,
    PendingEmails: 357,
    Recipients: 534,
    RemovedCell: 838,
    RemovedEmails: 571,
    RestrictedEmails: 688,
    SubAccountID: 99,
    TotalRecipients: 528,
    GroupName: "Barbra Lopez",
    UpdatedDate: "2016-04-09T04:46:31 -06:-30",
    CreatedDate: "2015-05-31T05:05:56 -06:-30",
    IsAutoResponder: false,
    IsConnectedToWebForm: false,
    AutomationID: null
  },
  {
    ActiveCell: 872,
    ActiveEmails: 794,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 715956,
    InvalidCell: 831,
    InvalidEmails: 556,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 694,
    Recipients: 605,
    RemovedCell: 625,
    RemovedEmails: 776,
    RestrictedEmails: 598,
    SubAccountID: 48,
    TotalRecipients: 198,
    GroupName: "Mejia Mills",
    UpdatedDate: "2021-08-17T01:33:28 -06:-30",
    CreatedDate: "2018-09-03T11:43:00 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 200,
    ActiveEmails: 583,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 827193,
    InvalidCell: 142,
    InvalidEmails: 381,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 666,
    Recipients: 17,
    RemovedCell: 340,
    RemovedEmails: 949,
    RestrictedEmails: 934,
    SubAccountID: 170,
    TotalRecipients: 304,
    GroupName: "Mcmillan Jenkins",
    UpdatedDate: "2018-02-11T11:03:51 -06:-30",
    CreatedDate: "2022-02-06T04:02:39 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 884,
    ActiveEmails: 512,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 451184,
    InvalidCell: 940,
    InvalidEmails: 446,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 179,
    Recipients: 379,
    RemovedCell: 430,
    RemovedEmails: 156,
    RestrictedEmails: 780,
    SubAccountID: 7,
    TotalRecipients: 621,
    GroupName: "Bray Bell",
    UpdatedDate: "2014-08-10T08:30:25 -06:-30",
    CreatedDate: "2014-11-10T02:20:12 -06:-30",
    IsAutoResponder: false,
    IsConnectedToWebForm: false,
    AutomationID: null
  },
  {
    ActiveCell: 183,
    ActiveEmails: 493,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 936792,
    InvalidCell: 66,
    InvalidEmails: 279,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 706,
    Recipients: 365,
    RemovedCell: 479,
    RemovedEmails: 419,
    RestrictedEmails: 266,
    SubAccountID: 450,
    TotalRecipients: 395,
    GroupName: "Brown Banks",
    UpdatedDate: "2019-04-19T08:28:11 -06:-30",
    CreatedDate: "2021-08-01T09:32:40 -06:-30",
    IsAutoResponder: false,
    IsConnectedToWebForm: false,
    AutomationID: null
  },
  {
    ActiveCell: 457,
    ActiveEmails: 827,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 182670,
    InvalidCell: 530,
    InvalidEmails: 193,
    IsDynamic: false,
    IsTestGroup: null,
    PendingEmails: 671,
    Recipients: 469,
    RemovedCell: 154,
    RemovedEmails: 736,
    RestrictedEmails: 756,
    SubAccountID: 525,
    TotalRecipients: 52,
    GroupName: "Opal Case",
    UpdatedDate: "2018-05-31T07:25:09 -06:-30",
    CreatedDate: "2018-06-08T06:18:53 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: false,
    AutomationID: null
  },
  {
    ActiveCell: 650,
    ActiveEmails: 565,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 983492,
    InvalidCell: 21,
    InvalidEmails: 90,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 753,
    Recipients: 875,
    RemovedCell: 19,
    RemovedEmails: 71,
    RestrictedEmails: 843,
    SubAccountID: 429,
    TotalRecipients: 74,
    GroupName: "Cohen Mccarthy",
    UpdatedDate: "2018-08-09T02:50:28 -06:-30",
    CreatedDate: "2017-05-31T03:45:47 -06:-30",
    IsAutoResponder: false,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 275,
    ActiveEmails: 577,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 324693,
    InvalidCell: 274,
    InvalidEmails: 833,
    IsDynamic: false,
    IsTestGroup: null,
    PendingEmails: 316,
    Recipients: 275,
    RemovedCell: 829,
    RemovedEmails: 633,
    RestrictedEmails: 382,
    SubAccountID: 598,
    TotalRecipients: 32,
    GroupName: "Silva Holloway",
    UpdatedDate: "2015-09-14T02:37:55 -06:-30",
    CreatedDate: "2016-03-29T04:05:44 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 452,
    ActiveEmails: 204,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 652985,
    InvalidCell: 374,
    InvalidEmails: 264,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 260,
    Recipients: 652,
    RemovedCell: 200,
    RemovedEmails: 425,
    RestrictedEmails: 517,
    SubAccountID: 715,
    TotalRecipients: 382,
    GroupName: "Kristine Ramirez",
    UpdatedDate: "2019-10-29T01:08:52 -06:-30",
    CreatedDate: "2015-11-22T04:09:21 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 664,
    ActiveEmails: 301,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 114051,
    InvalidCell: 567,
    InvalidEmails: 518,
    IsDynamic: false,
    IsTestGroup: null,
    PendingEmails: 844,
    Recipients: 999,
    RemovedCell: 114,
    RemovedEmails: 822,
    RestrictedEmails: 790,
    SubAccountID: 428,
    TotalRecipients: 857,
    GroupName: "Concepcion Sanford",
    UpdatedDate: "2016-07-21T11:35:21 -06:-30",
    CreatedDate: "2022-01-08T11:45:33 -06:-30",
    IsAutoResponder: false,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 287,
    ActiveEmails: 442,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 602466,
    InvalidCell: 499,
    InvalidEmails: 188,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 189,
    Recipients: 484,
    RemovedCell: 648,
    RemovedEmails: 54,
    RestrictedEmails: 963,
    SubAccountID: 253,
    TotalRecipients: 957,
    GroupName: "Hickman Bentley",
    UpdatedDate: "2017-08-09T12:25:55 -06:-30",
    CreatedDate: "2019-12-16T04:13:49 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 816,
    ActiveEmails: 645,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 188716,
    InvalidCell: 894,
    InvalidEmails: 151,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 760,
    Recipients: 939,
    RemovedCell: 138,
    RemovedEmails: 107,
    RestrictedEmails: 583,
    SubAccountID: 585,
    TotalRecipients: 88,
    GroupName: "Leta Williamson",
    UpdatedDate: "2016-07-25T03:25:25 -06:-30",
    CreatedDate: "2018-04-15T10:52:01 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 628,
    ActiveEmails: 422,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 937434,
    InvalidCell: 875,
    InvalidEmails: 55,
    IsDynamic: false,
    IsTestGroup: null,
    PendingEmails: 119,
    Recipients: 456,
    RemovedCell: 562,
    RemovedEmails: 389,
    RestrictedEmails: 940,
    SubAccountID: 219,
    TotalRecipients: 385,
    GroupName: "Guerrero Parrish",
    UpdatedDate: "2019-10-11T01:46:25 -06:-30",
    CreatedDate: "2021-03-20T10:37:11 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: false,
    AutomationID: null
  },
  {
    ActiveCell: 126,
    ActiveEmails: 629,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 825098,
    InvalidCell: 968,
    InvalidEmails: 679,
    IsDynamic: false,
    IsTestGroup: null,
    PendingEmails: 874,
    Recipients: 148,
    RemovedCell: 678,
    RemovedEmails: 477,
    RestrictedEmails: 913,
    SubAccountID: 963,
    TotalRecipients: 875,
    GroupName: "Avila Ross",
    UpdatedDate: "2020-09-24T12:50:32 -06:-30",
    CreatedDate: "2019-07-29T10:14:37 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
  {
    ActiveCell: 676,
    ActiveEmails: 473,
    DynamicData: null,
    DynamicLastUpdate: null,
    DynamicUpdatePolicy: null,
    GroupID: 920988,
    InvalidCell: 839,
    InvalidEmails: 763,
    IsDynamic: true,
    IsTestGroup: null,
    PendingEmails: 416,
    Recipients: 32,
    RemovedCell: 451,
    RemovedEmails: 920,
    RestrictedEmails: 24,
    SubAccountID: 570,
    TotalRecipients: 996,
    GroupName: "Nicole Haney",
    UpdatedDate: "2014-06-24T02:46:45 -06:-30",
    CreatedDate: "2020-06-01T08:02:50 -06:-30",
    IsAutoResponder: true,
    IsConnectedToWebForm: true,
    AutomationID: null
  },
];

export const ExcelData = [
  {
    SMSStatus: false,
    CreationDate: new Date(),
    FirstName: "dfdsf",
    Name: "fdsdfds",
    Email: "dfsdfsd",
    Telephone: 2332,
    Cellphone: 65465,
    Address: "dsdsfsdf",
    BirthdayDate: new Date(),
    City: "fdfdfg",
    State: "gfdgfd",
    Country: "dfgdfg",
    Zip: 5435,
    Company: "dfgdfgdf",
    ReminderDate: new Date(),
    ErrorMessage: "dgdfgdfg",
  },
  {
    SMSStatus: true,
    CreationDate: new Date(),
    FirstName: "dsfa",
    Name: "sfdds",
    Email: "dsfds",
    Telephone: 35435345,
    Cellphone: 3434324,
    Address: "fsdfsdfsdf",
    BirthdayDate: new Date(),
    City: "fdfsd",
    State: "sdasd",
    Country: "dsadda",
    Zip: 87987,
    Company: "sadad",
    ReminderDate: new Date(),
    ErrorMessage: "sdadafsa",
  },
];

export const UploadSettings = {
  SMS: {
    ShowGroupName: true,
    Fields: [
      {
        isdisabled: false,
        idx: -1,
        value: "FirstName",
        label: "common.first_name"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "LastName",
        label: "common.last_name"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "CellPhone",
        label: "common.cellphone"
      }
    ]
  },
  GROUPS: {
    ShowGroupName: false,
    Fields: [
      {
        isdisabled: false,
        idx: -1,
        value: "FirstName",
        label: "common.first_name"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "LastName",
        label: "common.last_name"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "CellPhone",
        label: "common.cellphone"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "Email",
        label: "common.email"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "Telephone",
        label: "common.telephone"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "Address",
        label: "common.address"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "City",
        label: "common.city"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "State",
        label: "common.state"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "Country",
        label: "common.country"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "Zip",
        label: "common.zip"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "Company",
        label: "common.company"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "BirthDate",
        label: "common.birth_date"
      },
      {
        isdisabled: false,
        idx: -1,
        value: "ReminderDate",
        label: "common.reminder_date"
      }
    ]
  }

};


export const simplyCLubClientData = [
  {
    "qa_seg_test": [
      {
        "ClientID": "626b8479926753649e2d31d2",
        "SubAccountID": "626b8479dc9d22c49042d34b",
        "Email": "perezoneil@turnling.com",
        "Status": false,
        "SmsStatus": true,
        "FirstName": "Barr",
        "LastName": "Colon",
        "Telephone": "+1 (831) 513-3794",
        "Cellphone": "+1 (847) 406-2632",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "715 Dupont Street, Gallina, Nebraska, 8073",
        "City": "Eastmont",
        "State": "Georgia",
        "Country": "Slovenia",
        "Zip": 7887,
        "Company": "KRAGGLE",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b84796305c0eae878d3cf",
        "SubAccountID": "626b847931b8433901206c12",
        "Email": "barrcolon@kraggle.com",
        "Status": true,
        "SmsStatus": false,
        "FirstName": "Velma",
        "LastName": "Clements",
        "Telephone": "+1 (950) 470-3781",
        "Cellphone": "+1 (811) 464-3042",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "410 Dorset Street, Concho, Virgin Islands, 3537",
        "City": "Bellfountain",
        "State": "California",
        "Country": "Bahamas",
        "Zip": 1926,
        "Company": "BUGSALL",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b8479b4992f5bf9fe1d5b",
        "SubAccountID": "626b847977c75442996f04fe",
        "Email": "velmaclements@bugsall.com",
        "Status": true,
        "SmsStatus": true,
        "FirstName": "Romero",
        "LastName": "Kim",
        "Telephone": "+1 (889) 465-2968",
        "Cellphone": "+1 (935) 408-3367",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "372 Clarkson Avenue, Summerset, Marshall Islands, 7395",
        "City": "Gasquet",
        "State": "North Dakota",
        "Country": "Tuvalu",
        "Zip": 2132,
        "Company": "VETRON",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b84796c51542b2dd0841f",
        "SubAccountID": "626b8479fba80b14947df4a9",
        "Email": "romerokim@vetron.com",
        "Status": true,
        "SmsStatus": false,
        "FirstName": "Tiffany",
        "LastName": "Odom",
        "Telephone": "+1 (858) 480-3879",
        "Cellphone": "+1 (860) 475-3935",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "848 Fenimore Street, Worton, Iowa, 4785",
        "City": "Greenbackville",
        "State": "Illinois",
        "Country": "Monaco",
        "Zip": 4727,
        "Company": "QUOTEZART",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b847999f060db2dd138c4",
        "SubAccountID": "626b847908fba1b7041f0d8c",
        "Email": "tiffanyodom@quotezart.com",
        "Status": true,
        "SmsStatus": false,
        "FirstName": "Bobbi",
        "LastName": "Guzman",
        "Telephone": "+1 (807) 495-3177",
        "Cellphone": "+1 (936) 447-2282",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "138 Irving Place, Westphalia, Texas, 6685",
        "City": "Wright",
        "State": "Wisconsin",
        "Country": "Cameroon",
        "Zip": 3278,
        "Company": "HOTCAKES",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b84795f7f1c820d87c8ba",
        "SubAccountID": "626b8479531cf35405f26aeb",
        "Email": "bobbiguzman@hotcakes.com",
        "Status": false,
        "SmsStatus": true,
        "FirstName": "Velazquez",
        "LastName": "Yates",
        "Telephone": "+1 (954) 460-2902",
        "Cellphone": "+1 (878) 527-2058",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "265 Matthews Place, Singer, Maine, 8334",
        "City": "Northridge",
        "State": "Florida",
        "Country": "Pitcairn",
        "Zip": 2075,
        "Company": "MOREGANIC",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      }
    ]
  },
  {
    "seg_prod_bb": [
      {
        "ClientID": "626b8479c00c2e82cc544110",
        "SubAccountID": "626b8479f4db007f1412cc8a",
        "Email": "velazquezyates@moreganic.com",
        "Status": true,
        "SmsStatus": true,
        "FirstName": "Bethany",
        "LastName": "Luna",
        "Telephone": "+1 (895) 446-3119",
        "Cellphone": "+1 (932) 580-3150",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "567 Vanderbilt Street, Coloma, Oklahoma, 235",
        "City": "Bennett",
        "State": "Montana",
        "Country": "Argentina",
        "Zip": 6644,
        "Company": "ESCENTA",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b847960cd6409345f311d",
        "SubAccountID": "626b8479daa2b9fd80944525",
        "Email": "bethanyluna@escenta.com",
        "Status": false,
        "SmsStatus": false,
        "FirstName": "Garner",
        "LastName": "David",
        "Telephone": "+1 (895) 431-3696",
        "Cellphone": "+1 (830) 483-3876",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "239 Boerum Place, Bangor, American Samoa, 4999",
        "City": "Conway",
        "State": "Massachusetts",
        "Country": "Ghana",
        "Zip": 7820,
        "Company": "ECRATER",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      }
    ]
  },
  {
    "sub emp": [
      {
        "ClientID": "626b8479911888f45953c438",
        "SubAccountID": "626b8479315b3cbb39317eea",
        "Email": "garnerdavid@ecrater.com",
        "Status": true,
        "SmsStatus": true,
        "FirstName": "Bryant",
        "LastName": "Hays",
        "Telephone": "+1 (938) 560-2696",
        "Cellphone": "+1 (855) 596-3605",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "545 Kermit Place, Harold, South Dakota, 4215",
        "City": "Coultervillle",
        "State": "District Of Columbia",
        "Country": "Guyana",
        "Zip": 8143,
        "Company": "EXTREMO",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      }
    ]
  },
  {
    "shri's gg": [
      {
        "ClientID": "626b8479397367e309814e71",
        "SubAccountID": "626b8479d60d146fe64174b5",
        "Email": "bryanthays@extremo.com",
        "Status": false,
        "SmsStatus": false,
        "FirstName": "Iris",
        "LastName": "Clark",
        "Telephone": "+1 (999) 596-3166",
        "Cellphone": "+1 (979) 427-3494",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "888 Eldert Lane, Cliffside, Arizona, 8230",
        "City": "Lodoga",
        "State": "Northern Mariana Islands",
        "Country": "Svalbard and Jan Mayen Islands",
        "Zip": 9372,
        "Company": "COSMOSIS",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b84794a82aff604145ab9",
        "SubAccountID": "626b8479adda0b65905d6516",
        "Email": "irisclark@cosmosis.com",
        "Status": true,
        "SmsStatus": false,
        "FirstName": "Burke",
        "LastName": "Livingston",
        "Telephone": "+1 (960) 413-2963",
        "Cellphone": "+1 (997) 590-3478",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "639 Montauk Avenue, Belva, Idaho, 8743",
        "City": "Grantville",
        "State": "Alabama",
        "Country": "Saudi Arabia",
        "Zip": 3249,
        "Company": "INQUALA",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b8479dce3ad7fcd4a2c73",
        "SubAccountID": "626b8479490899ee838759bd",
        "Email": "burkelivingston@inquala.com",
        "Status": true,
        "SmsStatus": false,
        "FirstName": "Clemons",
        "LastName": "Patrick",
        "Telephone": "+1 (947) 513-3562",
        "Cellphone": "+1 (953) 557-3547",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "802 Kingsland Avenue, Troy, Hawaii, 2518",
        "City": "Taycheedah",
        "State": "Alaska",
        "Country": "South Africa",
        "Zip": 9137,
        "Company": "ACUSAGE",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      }
    ]
  },
  {
    "Group basket": [
      {
        "ClientID": "626b84797570ae829bdecb3e",
        "SubAccountID": "626b8479f662e0e1536aa183",
        "Email": "clemonspatrick@acusage.com",
        "Status": true,
        "SmsStatus": false,
        "FirstName": "White",
        "LastName": "Allison",
        "Telephone": "+1 (870) 424-2687",
        "Cellphone": "+1 (922) 415-2391",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "768 Beadel Street, Teasdale, New Jersey, 8088",
        "City": "Edenburg",
        "State": "Virginia",
        "Country": "United Kingdom",
        "Zip": 9420,
        "Company": "FUTURITY",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b847997d55caba583bb99",
        "SubAccountID": "626b84793539e68dbfe2b43a",
        "Email": "whiteallison@futurity.com",
        "Status": true,
        "SmsStatus": true,
        "FirstName": "Finch",
        "LastName": "Sandoval",
        "Telephone": "+1 (925) 503-3020",
        "Cellphone": "+1 (938) 441-3668",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "651 Johnson Street, Yogaville, Pennsylvania, 1140",
        "City": "Kapowsin",
        "State": "Oregon",
        "Country": "Zaire",
        "Zip": 7338,
        "Company": "GLASSTEP",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      },
      {
        "ClientID": "626b847936b7a50775d0098a",
        "SubAccountID": "626b8479eae3433d26148630",
        "Email": "finchsandoval@glasstep.com",
        "Status": false,
        "SmsStatus": true,
        "FirstName": "Eunice",
        "LastName": "Hayden",
        "Telephone": "+1 (806) 440-3744",
        "Cellphone": "+1 (813) 589-3887",
        "CellphoneRightDigits": "סימפלי 1",
        "Address": "622 Norman Avenue, Leola, Nevada, 4046",
        "City": "Lafferty",
        "State": "North Carolina",
        "Country": "Cambodia",
        "Zip": 9208,
        "Company": "RETRACK",
        "ExtraFields": null,
        "BirthDate": "<ReferenceError: min is not defined>",
        "ReminderDate": "<ReferenceError: min is not defined>",
        "LastSendDate": "<ReferenceError: min is not defined>",
        "CreationDate": "<ReferenceError: min is not defined>",
        "FailedSendingCounter": null,
        "IsWebService": null,
        "LastEmailOpened": null,
        "LastEmailClicked": null,
        "BestEmailOpenTime": null
      }
    ]
  }
]