export enum eSMSType {
    Text = 0,
    WAP = 1
}
export enum eSmsCountry {
    Global = 0,
    Israel = 1,
    Mexico = 2
}
export enum eSMSProvider {
    Unicell = 1,
    CardboardFish,
    inforuMobile = 3,
    TelZar,
    Mobiweb = 5,
    BLANK,
    SilverStreet,
    Pelephone,
    Telzar201,
    SimpleSMS,
    MessageBird,
    SmsWarriors,
    Pelephone2,
    Pelephone3,
    Speedflow = 15,
    Bulkness = 16,
    SmsGlory = 17,
    MrMessaging = 18,
    MrMessagingAdvanced = 19,
    SimpleSMS2 = 20,
    SimpleSMS3 = 21,
    SimpleSMSMobi = 22,
    Mgage = 23,
    SimpleSMS4 = 24,
    SimpleSMS5 = 25,
    MessageBirdOmer = 26,
    MMD = 27,
    MrMessagingCellForce = 28,
    SimpleDTS = 29,
    BSG1 = 30,
    BSG2 = 31,
    MMAOmer = 32,
    SimpleOTP = 33,
    SimpleOTP2 = 45,
    MessageCloud = 34,
    PaycallSmpp = 36,
    Dimoco = 37,
    Broadnet = 38,
    TelzarLongMessages = 39,
    PelephoneOTP = 40,
    PelephoneIBM = 41,
    Pelephon2Idan = 42,
    SimpleSpeech = 43,
    SimpleComp = 44,
    SimpleOTPSasi = 901,
    SimpleBulk = 46
}
export enum eSmsStatus {
    TakenBySender = -1,
    Pending = 1,
    Sent = 2,
    Success = 3,
    Failure = 4,
    Removed = 5,
    Stopped = 6,
    Canceled = 7,
    Deleted = 8,
    Suspended = 9,
    RequireAproval = 10,
    InvalidFromNumber = 12,
    ToNumberLonger = 13,
    BlockedDueToSyncFeature = 20,
    BlockedDueToRemoval = 21,
}
