export const appearance = {
    panels: {
        dock: 'right'
    }
}
export const tools = {
    html: {
        enabled: true
    },
    social: {
        enabled: true
    },
    timer: {
        enabled: true
    },
    video: {
        enabled: true
    },
    form: {
        enabled: true,
        usageLimit: 1,
        properties: {
            fields: { // Put pulseem defaults here
                editor: {
                    data: {
                        defaultFields: [
                            { name: "birthday", label: "Birthday", type: "date" },
                            { name: "company", label: "Company", type: "text" },
                            { name: "email", label: "Email", type: "email" },
                            { name: "first_name", label: "First Name", type: "text" },
                            { name: "last_name", label: "Last Name", type: "text" },
                            { name: "phone_number", label: "Phone Number", type: "text" },
                            { name: "website", label: "Website", type: "text" },
                            { name: "zip_code", label: "Zip Code", type: "text" }
                        ]
                    }
                }
            },
            action: {
                editor: {
                    data: {
                        actions: [
                            {
                                label: 'Marketing',
                                method: 'POST',
                                url: 'http://whatever.com/marketing-form-submission',
                            },
                            {
                                label: 'Sales',
                                method: 'POST',
                                target: '_blank',
                                url: 'http://whatever.com/sales-form-submission',
                            }
                        ]
                    }
                }
            }
        }
    }
};
export const options = {
    amp: true,
    locale: "he-IL",
    translations:
    {
      'he-IL':  {
        "buttons.add_column": "הוסף עמודה",
        "buttons.add_content": "הוסף תוכן",
        "buttons.add_display_condition": "Add Display Condition",
        "buttons.add_field": "הוסף שדה",
        "buttons.add_new_field": "הוסף שדה חדש",
        "buttons.add_new_item": "Add New Item",
        "buttons.add_row": "הוסף שורה",
        "buttons.add_text": "הוסף טקסט",
        "buttons.apply": "החל",
        "buttons.apply_effects": "החלת אפקטים ועוד",
        "buttons.back": "חזור",
        "buttons.background": "רקע",
        "buttons.cancel": "ביטול",
        "buttons.change": "שינוי",
        "buttons.change_image": "שנה תמונה",
        "buttons.close": "סגור",
        "buttons.comment": "תגובה",
        "buttons.corners": "קרנות",
        "buttons.crop": "חתוך",
        "buttons.delete": "מחק",
        "buttons.deselect": "Deselect",
        "buttons.desktop": "דסקטופ",
        "buttons.done": "סיום",
        "buttons.draw": "צייר",
        "buttons.drawing": "ציור",
        "buttons.duplicate": "שכפול",
        "buttons.duplication_disabled_usage_limit": "You cannot duplicate this due to a usage limit",
        "buttons.edit": "עריכה",
        "buttons.filter": "סינון",
        "buttons.frame": "מסגרת",
        "buttons.history": "הסטוריה",
        "buttons.merge": "מיזוג",
        "buttons.mobile": "נייד",
        "buttons.more_options": "אפשרויות נוספות",
        "buttons.open": "פתיחה",
        "buttons.remove_column": "הסר עמודה",
        "buttons.reset": "אתחול",
        "buttons.reset_value": "אתחל ערך",
        "buttons.resize": "Resize",
        "buttons.save": "שמירה",
        "buttons.select": "בחירה",
        "buttons.shape": "תבנית",
        "buttons.shapes": "תבניות",
        "buttons.show_fewer_options": "הצג פחות אפשרויות",
        "buttons.show_more_options": "הצג אפרשרויות נוספות",
        "buttons.sticker": "סטיקר",
        "buttons.stickers": "סטיקרים",
        "buttons.tablet": "טאבלט",
        "buttons.transform": "Transform",
        "buttons.update_field": "עדכן שדה",
        "buttons.upload": "העלאה",
        "buttons.upload_image": "העלה תמונה",
        "buttons.zoom": "זום",
        "collaboration.add_comment": "הוסף תגובה",
        "collaboration.empty.subtitle": "Your threads here",
        "collaboration.empty.title": "Team collaboration made easy!",
        "collaboration.empty_filtered.subtitle": "matching your filters",
        "collaboration.empty_filtered.title": "No threads found",
        "collaboration.exit_mode": "סגור תגובות",
        "collaboration.filters.all": "הכל",
        "collaboration.filters.only_yours": "שלך בלבד",
        "collaboration.filters.resolved": "נפתר",
        "collaboration.follow_docs_to_setup": "Follow the docs to setup team collaboration",
        "collaboration.leave_repply": "השאר תגובה",
        "collaboration.login_to_collaborate": "You need to be logged in to be able to collaborate",
        "collaboration.panel.threads": "Threads",
        "collaboration.replies.one": "תגובה אחת",
        "collaboration.replies.n": "{n} תגובות",
        "collaboration.replies.none": "אין תגובות",
        "collaboration.resolve": "Resolve",
        "collaboration.resolved": "Resolved",
        "collaboration.types.feedback": "Feedback",
        "collaboration.types.idea": "Idea",
        "collaboration.types.question": "שאלה",
        "collaboration.types.urgent": "דחוף",
        "colors.black": "שחור",
        "colors.ruby": "Ruby",
        "colors.white": "לבן",
        "content_tools.button": "כפתור",
        "content_tools.columns": "עמודות",
        "content_tools.divider": "קו מפריד",
        "content_tools.form": "טופס",
        "content_tools.heading": "כותרת",
        "content_tools.html": "HTML",
        "content_tools.image": "תמונה",
        "content_tools.menu": "תפריט",
        "content_tools.social": "מדיה חברתית",
        "content_tools.text": "טקסט",
        "content_tools.timer": "שעון עצר",
        "content_tools.video": "וידאו",
        "editor.action_type.label": "Action Type",
        "editor.align.label": "יישר",
        "editor.alignment.label": "יישור",
        "editor.all_sides.label": "כל הצדדים",
        "editor.alternate_text.label": "Alternate Text",
        "editor.anchor.section_already_exists": "A page section with this name already exists",
        "editor.background_color.label": "צבע רקע",
        "editor.background_image.center": "מרכז",
        "editor.background_image.cover_mode": "Cover Mode",
        "editor.background_image.full_width": "כל הרוחב",
        "editor.background_image.label": "תמונת רקע",
        "editor.background_image.repeat": "Repeat",
        "editor.border.dashed": "Dashed",
        "editor.border.dotted": "Dotted",
        "editor.border.label": "Border",
        "editor.border.solid": "Solid",
        "editor.bottom.label": "Bottom",
        "editor.bottom_left.label": "Bottom Left",
        "editor.bottom_right.label": "Bottom Right",
        "editor.button_link.label": "Button Link",
        "editor.color.label": "צבע",
        "editor.colors.label": "צבעים",
        "editor.columns_background.label": "רקע עמודה",
        "editor.container_padding.label": "Container Padding",
        "editor.content_alignment.label": "יישור תוכן",
        "editor.content_background_color.label": "צבע רקע תוכן",
        "editor.content_width.label": "רוחב תוכן",
        "editor.digits_color.label": "Digits Color",
        "editor.digits_font.label": "Digits Font",
        "editor.digits_font_size.label": "Digits Font Size",
        "editor.do_not_stack_on_mobile.label": "Do Not Stack on Mobile",
        "editor.end_time.label": "End Time",
        "editor.fields.label": "שדות",
        "editor.font_family.label": "Font Family",
        "editor.font_size.label": "גודל פונטים",
        "editor.form.custom": "Custom",
        "editor.form.method": "Method",
        "editor.form_alignment.label": "יישור טופס",
        "editor.form_width.label": "רוחב הטופס",
        "editor.full_width.label": "רוחב מירבי",
        "editor.heading_type.label": "סוג כותרת",
        "editor.height.label": "גובה",
        "editor.hide_on_desktop.label": "הסתר בדסקטופ",
        "editor.hide_on_mobile.label": "הסתר בנייד",
        "editor.hover_background.label": "Hover Background",
        "editor.hover_color.label": "Hover Color",
        "editor.hover_text.label": "Hover Text",
        "editor.hover_underline.label": "Hover Underline",
        "editor.icon_spacing.label": "Icon Spacing",
        "editor.icon_type.label": "Icon Type",
        "editor.image.added_drawing": "Added: drawing",
        "editor.image.added_frame": "Added: frame",
        "editor.image.added_overlay_image": "Added: overlay image",
        "editor.image.added_shape": "Added: shape",
        "editor.image.added_sticker": "Added: sticker",
        "editor.image.added_text": "Added: text",
        "editor.image.applied_crop": "Applied: crop",
        "editor.image.applied_filter": "Applied: filter",
        "editor.image.applied_resize": "Applied: resize",
        "editor.image.applied_rounded_corners": "Applied: rounded corners",
        "editor.image.applied_transform": "Applied: transform",
        "editor.image.auto": "אטוטומטי",
        "editor.image.auto_width": "רוחב אוטומטי",
        "editor.image.auto_width_switch_off": "Switch off auto width to manually resize the image",
        "editor.image.brush_color": "צבע מברשת",
        "editor.image.brush_size": "גודל מברשת",
        "editor.image.brush_type": "סוג מברשת",
        "editor.image.canvas_background": "רקע קנבס",
        "editor.image.changed_background": "Changed: background",
        "editor.image.changed_background_image": "Changed: background image",
        "editor.image.changed_style": "Changed: style",
        "editor.image.drop_upload": "Drop a new image here, or click to select files to upload.",
        "editor.image.full_width_mobile": "רוחב מירבי בנייד",
        "editor.image.image_options": "אפשרויות תמונה",
        "editor.image.image_url": "קישור לתמונה",
        "editor.image.initial": "Initial",
        "editor.image.label": "תמונה",
        "editor.image.loaded_state": "Loaded: state",
        "editor.image.maintain_aspect_ratio": "Maintain Aspect Ratio",
        "editor.image.main_image": "תמונה ראשית",
        "editor.image.objects_merged": "Objects: merged",
        "editor.image.offset_x": "Offset X",
        "editor.image.offset_y": "Offset Y",
        "editor.image.outline_width": "Outline Width",
        "editor.image.uploading": "Uploading",
        "editor.image.upload_error": "There was an error uploading your image. Make sure it's a valid image file with size under {mbSize} MB.",
        "editor.image.use_percentages": "השתמש באחוזים",
        "editor.image_link.label": "קישור לתמונה",
        "editor.inherit_body_styles.label": "Inherit Body Styles",
        "editor.labels.web": "Web",
        "editor.labels_color.label": "Labels Color",
        "editor.labels_font.label": "Labels Font",
        "editor.labels_font_size.label": "Labels Font Size",
        "editor.layout.label": "Layout",
        "editor.left.label": "שמאל",
        "editor.line.label": "Line",
        "editor.line_height.label": "Line Height",
        "editor.link.body": "Body",
        "editor.link.call_phone": "מספר נייד",
        "editor.link.mailto": "אימייל ל",
        "editor.link.new_tab": "חלונית חדשה",
        "editor.link.no_page_sections_found": "No page sections found",
        "editor.link.onclick_unsupported": "OnClick is not supported",
        "editor.link.open_website": "Open Website",
        "editor.link.page_section": "Go to Page Section",
        "editor.link.phone": "טלפון",
        "editor.link.same_tab": "באותו חלון",
        "editor.link.send_email": "שלח מייל",
        "editor.link.send_sms": "שלח SMS",
        "editor.link.subject": "נושא",
        "editor.link.target": "Target",
        "editor.link.url": "URL",
        "editor.link_color.label": "צבע הקישור",
        "editor.margin.label": "Margin",
        "editor.mobile.description": "You are currently editing for Mobile devices. Switch to Desktop for all styling options.",
        "editor.offline_mode_is_enabled": "Offline mode is enabled",
        "editor.padding.label": "Padding",
        "editor.placeholder.text": "No content here. Drag content from right.",
        "editor.placeholder.text.left": "No content here. Drag content from left.",
        "editor.play_icon_color.label": "Play Icon Color",
        "editor.play_icon_size.label": "Play Icon Size",
        "editor.play_icon_type.label": "Play Icon Type",
        "editor.preheader_text.description": "A preheader is the short summary text that follows the subject line when viewing an email from the inbox.",
        "editor.preheader_text.label": "Preheader Text",
        "editor.right.label": "ימין",
        "editor.rounded_border.label": "Rounded Border",
        "editor.section_name.description": "A section name is used for linking within a page. It serves as an anchor for buttons or links.",
        "editor.section_name.label": "Section Name",
        "editor.separator.label": "Separator",
        "editor.social_links.label": "Social Links",
        "editor.space_between_fields.label": "ריווח שדות",
        "editor.submit_action.label": "Submit Action",
        "editor.text.label": "טקסט",
        "editor.text_align.label": "יישור טקסט",
        "editor.text_color.label": "צבע טקסט",
        "editor.top.label": "Top",
        "editor.top_left.label": "Top Left",
        "editor.top_right.label": "Top Right",
        "editor.underline.label": "Underline",
        "editor.video.arrow_only": "Arrow Only",
        "editor.video.video_camera": "מצלמת וידאו",
        "editor.video_url.description": "Add a YouTube or Vimeo URL to automatically generate a preview image. The image will link to the provided URL.",
        "editor.video_url.label": "קישור לוידאו",
        "editor.width.label": "רוחב",
        "editors_panel.title.content": "תוכן",
        "editors_panel.title.contents": "תכנים",
        "editors_panel.title.rows": "שורה",
        "fields.birthday": "תאריך לידה",
        "fields.company": "חברה",
        "fields.name": "שם",
        "fields.phone_number": "מספר נייד",
        "fields.website": "אתר",
        "fields.zip_code": "מיקוד",
        "inbox_preview.design_updated": "Design has been updated after your last preview generation",
        "labels.align_text": "יישור טקסט",
        "labels.blur": "Blur",
        "labels.category": "Category",
        "labels.color_picker": "Color Picker",
        "labels.comments": "Comments",
        "labels.desktop_preview": "Desktop Preview",
        "labels.device_override": "This device is overriding values",
        "labels.display_conditions": "Display Conditions",
        "labels.editor": "עורך",
        "labels.font": "פונט",
        "labels.format_text": "Format Text",
        "labels.google_fonts": "Google Fonts",
        "labels.gradient": "Gradient",
        "labels.hide": "הסתר",
        "labels.horizontal": "Horizontal",
        "labels.language": "שפה",
        "labels.loading": "טוען",
        "labels.loading_images": "טוען תמונות",
        "labels.load_more": "טען עוד",
        "labels.menu.links": "תפריט קישורים",
        "labels.merge_tags": "תוכן אישי",
        "labels.mobile_preview": "תצוגת נייד",
        "labels.new": "חדש",
        "labels.no_images": "אין תמונות",
        "labels.no_results": "אין תוצאה",
        "labels.objects": "נושאים",
        "labels.outline": "Outline",
        "labels.page": "עמוד",
        "labels.radius": "רדיוס",
        "labels.redo": "Redo",
        "labels.safe_search": "חיפוש בטוח",
        "labels.search": "חיפוש",
        "labels.search_images": "Search millions of images",
        "labels.section": "Section",
        "labels.shadow": "צל",
        "labels.size": "גודל",
        "labels.something_went_wrong": "משהו השתבש",
        "labels.special_links": "קישורים נוספים",
        "labels.stock_photos_by": "Powered by Unsplash, Pexels, Pixabay.",
        "labels.stock_photos_license": "All images licensed under Creative Commons Zero.",
        "labels.stop": "עצור",
        "labels.tags": "תגיות",
        "labels.texture": "Texture",
        "labels.text_style": "סגנון טקסט",
        "labels.timezone": "Timezone",
        "labels.undo": "Undo",
        "labels.vertical": "Vertical",
        "modals.category.invalid": "This is an invalid category name",
        "modals.category.placeholder": "שם הקטגוריה",
        "modals.delete.columns": "You will lose {columns, number} {columns, plural, one {column} other {columns}}. Are you sure?",
        "modals.delete.confirmation": "Are you sure you want to delete this? This action cannot be undone.",
        "modals.delete.title": "מחק",
        "modals.display_conditions.title": "Select a Display Condition",
        "modals.preview.inbox_preview.button.generate_previews": "Generate Previews",
        "modals.preview.inbox_preview.label": "Inbox Previews",
        "modals.preview.inbox_preview.label.generating_again": "Generate again",
        "modals.preview.inbox_preview.label.generating_previews": "Generating previews",
        "modals.preview.inbox_preview.text.generate_previews": "Check how your template will look like in the inbox of different devices and email services.",
        "modals.preview.title": "תצוגה מקדימה",
        "modals.save_block.title": "שמור תבנית",
        "modals.tags.description": "Tags are used for searching. Multiple tags can be separated by a comma.",
        "modals.tags.placeholder": "תג1, תג2",
        "option_groups.action.title": "Action",
        "option_groups.all.title": "הכל",
        "option_groups.blank.title": "חדש",
        "option_groups.button.title": "כפתור",
        "option_groups.button_options.title": "אפשרויות כפתור",
        "option_groups.colors.title": "צבעים",
        "option_groups.columns.title": "עמודות",
        "option_groups.column_number.title": "עמודה {number}",
        "option_groups.column_properties.title": "מאפייני עמודה",
        "option_groups.countdown.title": "Countdown",
        "option_groups.default.title": "כללי",
        "option_groups.display_condition.title": "Display Condition",
        "option_groups.email_settings.title": "הגדרות מייל",
        "option_groups.fields.title": "שדות",
        "option_groups.form.title": "טופס",
        "option_groups.html.title": "HTML",
        "option_groups.icons.title": "אייקונים",
        "option_groups.image.title": "תמונה",
        "option_groups.labels.title": "Labels",
        "option_groups.last_saved.title": "נשמר לאחרונה",
        "option_groups.layout.title": "Layout",
        "option_groups.line.title": "Line",
        "option_groups.link.title": "קישור",
        "option_groups.links.title": "קישורים",
        "option_groups.menu_items.title": "Menu Items",
        "option_groups.mobile.title": "נייד",
        "option_groups.responsive_design.title": "עיצוב רספונסיבי",
        "option_groups.row_properties.title": "מאפייני שורה",
        "option_groups.size.title": "גודל",
        "option_groups.spacing.title": "מרווח",
        "option_groups.styles.title": "סגנונות",
        "option_groups.text.title": "טקסט",
        "shapes.circle": "Circle",
        "shapes.rectangle": "Rectangle",
        "shapes.round": "Round",
        "shapes.square": "Square",
        "sizes.large": "גדול",
        "sizes.largest": "גדול מאוד",
        "sizes.medium": "בינוני",
        "sizes.small": "קטן",
        "sizes.smallest": "קטן מאוד",
        "tabs.audit.empty.description": "Audit is where you can see all the issues in your design and content.",
        "tabs.audit.empty.subtitle": "It's all good!",
        "tabs.audit.empty.title": "No issues currently",
        "tabs.audit.missing_image_src": "חסר URL לתמונה",
        "tabs.audit.missing_title": "Missing audit title",
        "tabs.audit.missing_tool_name": "Tool name not found",
        "tabs.audit.rules.button.empty_links.description": "Without a link, buttons will not work when a user clicks on it. Add a link to the following buttons.",
        "tabs.audit.rules.button.empty_links.title": "Button links are empty",
        "tabs.audit.rules.image.alt_text.description": "Without alt text, people who rely on screen readers can’t access image information. Write an appropriate alternate text for the following imags.",
        "tabs.audit.rules.image.alt_text.title": "Missing alternate text",
        "tabs.audit.rules.image.url.description": "Without an image URL, the following images will not be rendered. Upload an image to the following images.",
        "tabs.audit.rules.image.url.title": "Missing images",
        "tabs.audit.rules.menu.empty_links.description": "Without a link, menu will not work when a user clicks on it. Add missing links to the following menu.",
        "tabs.audit.rules.menu.empty_links.title": "Menu links are empty",
        "tabs.audit.take_me_to_fix": "Take me to fix",
        "tools.form.field_label": "Field Label",
        "tools.form.field_name": "שם השדה",
        "tools.form.field_type": "סוג שדה",
        "tools.form.field_value": "ערך שדה",
        "tools.form.new_field": "שדה חדש",
        "tools.form.options_one_per_line": "אפשרויות (אחת בכל שורה)",
        "tools.form.placeholder_text": "Placeholder Text",
        "tools.form.required_field": "שדה חובה",
        "tools.form.show_label": "Show Label",
        "tools.form.update_field": "עדכן שדה",
        "tools.social.click_icons_to_add": "Click the icons to add",
        "tools.tabs.audit": "Audit",
        "tools.tabs.blocks": "תבניות",
        "tools.tabs.body": "Body",
        "tools.tabs.content": "תוכן",
        "tools.tabs.images": "תמונות",
        "tools.tabs.row": "שורה",
        "tools.tabs.uploads": "העלאות",
        "tools.text.personalize": "שדה אישי",
        "tools.tooltip.drag_on_canvas": "Drag on canvas",
        "tools.tooltip.got_it": "Got it"
      }
    }
}
export const features = {
    imageEditor: true,
    userUploads: true,
    pageAnchors: true,
    undoRedo: true,
    textEditor: {
        tables: true,
        emojis: true
    }
}
export const fonts = {
  fonts: {
    showDefaultFonts: false,
    customFonts: [
      {
        label: "Andale Mono",
        value: "andale mono,times"
      },
      {
        label: "Arial",
        value: "arial,helvetica,sans-serif"
      },
      {
        label: "Arial Black",
        value: "arial black,avant garde,arial"
      },
      {
        label: "Book Antiqua",
        value: "book antiqua,palatino"
      },
      {
        label: "Comic Sans MS",
        value: "comic sans ms,sans-serif"
      },
      {
        label: "Courier New",
        value: "courier new,courier"
      },
      {
        label: "Georgia",
        value: "georgia,palatino"
      },
      {
        label: "Helvetica",
        value: "helvetica,sans-serif"
      },
      {
        label: "Impact",
        value: "impact,chicago"
      },
      {
        label: "Symbol",
        value: "symbol"
      },
      {
        label: "Tahoma",
        value: "tahoma,arial,helvetica,sans-serif"
      },
      {
        label: "Terminal",
        value: "terminal,monaco"
      },
      {
        label: "Times New Roman",
        value: "times new roman,times"
      },
      {
        label: "Trebuchet MS",
        value: "trebuchet ms,geneva"
      },
      {
        label: "Verdana",
        value: "verdana,geneva"
      },
      {
        label: "Lobster Two",
        value: "'Lobster Two',cursive",
        url: "https://fonts.googleapis.com/css?family=Lobster+Two:400,700"
      },
      {
        label: "Playfair Display",
        value: "'Playfair Display',serif",
        url: "https://fonts.googleapis.com/css?family=Playfair+Display:400,700"
      },
      {
        label: "Rubik",
        value: "'Rubik',sans-serif",
        url: "https://fonts.googleapis.com/css?family=Rubik:400,700"
      },
      {
        label: "Source Sans Pro",
        value: "'Source Sans Pro',sans-serif",
        url: "https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700"
      },
      {
        label: "Open Sans",
        value: "'Open Sans',sans-serif",
        url: "https://fonts.googleapis.com/css?family=Open+Sans:400,700"
      },
      {
        label: "Crimson Text",
        value: "'Crimson Text',serif",
        url: "https://fonts.googleapis.com/css?family=Crimson+Text:400,700"
      },
      {
        label: "Montserrat",
        value: "'Montserrat',sans-serif",
        url: "https://fonts.googleapis.com/css?family=Montserrat:400,700"
      },
      {
        label: "Old Standard TT",
        value: "'Old Standard TT',serif",
        url: "https://fonts.googleapis.com/css?family=Old+Standard+TT:400,700"
      },
      {
        label: "Lato",
        value: "'Lato',sans-serif",
        url: "https://fonts.googleapis.com/css?family=Lato:400,700"
      },
      {
        label: "Raleway",
        value: "'Raleway',sans-serif",
        url: "https://fonts.googleapis.com/css?family=Raleway:400,700"
      },
      {
        label: "Cabin",
        value: "'Cabin',sans-serif",
        url: "https://fonts.googleapis.com/css?family=Cabin:400,700"
      },
      {
        label: "Pacifico",
        value: "'Pacifico',cursive",
        url: "https://fonts.googleapis.com/css?family=Pacifico"
      }
    ]
  }
}
